### ISSUE TITLE
This will not install?

### ISSUE THREAD

**Issue by nicgord** [pevandenburie/node-red-contrib-pcd8544-rpi#1]
Cannot install this successfully. Error  pcd8544_rpi install script 'node-gyp rebuild'.

does this work for anyone?

**Comment by nede-red-alex** [comment]
No, it does not work on my raspberry as well.
pi@raspberrypi:~ $ npm install node-red-contrib-pcd8544-rpi

> pcd8544_rpi@0.1.1 install /home/pi/node_modules/pcd8544_rpi
> node-gyp rebuild

make: Verzeichnis „/home/pi/node_modules/pcd8544_rpi/build“ wird betreten
  CXX(target) Release/obj.target/pcd8544_rpi/src/PCD8544.o
In file included from /usr/include/c++/6/utility:70:0,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/bits/stl_pair.h:415:21: error: macro "swap" requires 2 arguments, but only 1 given
       swap(pair& __p)
                     ^
/usr/include/c++/6/bits/stl_pair.h:475:50: error: macro "swap" passed 4 arguments, but takes just 2
     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
                                                  ^
/usr/include/c++/6/bits/stl_pair.h:476:35: error: macro "swap" requires 2 arguments, but only 1 given
     noexcept(noexcept(__x.swap(__y)))
                                   ^
/usr/include/c++/6/bits/stl_pair.h:477:19: error: macro "swap" requires 2 arguments, but only 1 given
     { __x.swap(__y); }
                   ^
In file included from /usr/include/c++/6/exception:172:0,
                 from /usr/include/c++/6/new:40,
                 from /usr/include/c++/6/ext/new_allocator.h:33,
                 from /usr/include/arm-linux-gnueabihf/c++/6/bits/c++allocator.h:33,
                 from /usr/include/c++/6/bits/allocator.h:46,
                 from /usr/include/c++/6/vector:61,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:22,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/bits/exception_ptr.h:122:68: error: macro "swap" requires 2 arguments, but only 1 given
         exception_ptr(static_cast<exception_ptr&&>(__o)).swap(*this);
                                                                    ^
/usr/include/c++/6/bits/exception_ptr.h:130:26: error: macro "swap" requires 2 arguments, but only 1 given
       swap(exception_ptr&) _GLIBCXX_USE_NOEXCEPT;
                          ^
/usr/include/c++/6/bits/exception_ptr.h:165:23: error: macro "swap" requires 2 arguments, but only 1 given
     { __lhs.swap(__rhs); }
                       ^
In file included from /usr/include/c++/6/vector:64:0,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:22,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/bits/stl_vector.h:1195:23: error: macro "swap" requires 2 arguments, but only 1 given
       swap(vector& __x) _GLIBCXX_NOEXCEPT
                       ^
/usr/include/c++/6/bits/stl_vector.h:1557:60: error: macro "swap" passed 4 arguments, but takes just 2
     swap(vector<_Tp, _Alloc>& __x, vector<_Tp, _Alloc>& __y)
                                                            ^
/usr/include/c++/6/bits/stl_vector.h:1558:49: error: macro "swap" requires 2 arguments, but only 1 given
     _GLIBCXX_NOEXCEPT_IF(noexcept(__x.swap(__y)))
                                                 ^
/usr/include/c++/6/bits/stl_vector.h:1559:19: error: macro "swap" requires 2 arguments, but only 1 given
     { __x.swap(__y); }
                   ^
In file included from /usr/include/c++/6/vector:65:0,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:22,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/bits/stl_bvector.h:930:21: error: macro "swap" requires 2 arguments, but only 1 given
     swap(vector& __x) _GLIBCXX_NOEXCEPT
                     ^
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected unqualified-id before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
In file included from /usr/include/c++/6/bits/move.h:57:0,
                 from /usr/include/c++/6/bits/stl_pair.h:59,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/type_traits:2606:5: error: expected unqualified-id before ‘noexcept’
     noexcept(__and_<is_nothrow_move_constructible<_Tp>,
     ^~~~~~~~
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected unqualified-id before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
In file included from /usr/include/c++/6/bits/move.h:57:0,
                 from /usr/include/c++/6/bits/stl_pair.h:59,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/type_traits:2613:5: error: expected unqualified-id before ‘noexcept’
     noexcept(__is_nothrow_swappable<_Tp>::value);
     ^~~~~~~~
/usr/include/c++/6/type_traits:2616:16: error: ‘std::swap’ has not been declared
     using std::swap;
                ^~~~
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected primary-expression before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
../src/PCD8544.h:52:20: error: expected ‘)’ before ‘{’ token
In file included from /usr/include/c++/6/bits/move.h:57:0,
                 from /usr/include/c++/6/bits/stl_pair.h:59,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/type_traits:2621:18: error: expected type-specifier before ‘decltype’
                = decltype(swap(std::declval<_Tp&>(), std::declval<_Tp&>()))>
                  ^~~~~~~~
/usr/include/c++/6/type_traits:2621:18: error: expected ‘>’ before ‘decltype’
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected unqualified-id before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
In file included from /usr/include/c++/6/bits/move.h:57:0,
                 from /usr/include/c++/6/bits/stl_pair.h:59,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/type_traits:2621:75: error: expected unqualified-id before ‘)’ token
                = decltype(swap(std::declval<_Tp&>(), std::declval<_Tp&>()))>
                                                                           ^
/usr/include/c++/6/type_traits:2632:19: error: template argument 1 is invalid
           noexcept(swap(std::declval<_Tp&>(), std::declval<_Tp&>()))
                   ^
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected unqualified-id before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
In file included from /usr/include/c++/6/bits/move.h:57:0,
                 from /usr/include/c++/6/bits/stl_pair.h:59,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/type_traits:2632:68: error: expected unqualified-id before ‘)’ token
           noexcept(swap(std::declval<_Tp&>(), std::declval<_Tp&>()))
                                                                    ^
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected unqualified-id before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
In file included from /usr/include/c++/6/bits/stl_pair.h:59:0,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/bits/move.h:180:5: error: expected unqualified-id before ‘noexcept’
     noexcept(__and_<is_nothrow_move_constructible<_Tp>,
     ^~~~~~~~
In file included from ../src/PCD8544.cc:45:0:
../src/PCD8544.h:52:20: error: expected unqualified-id before ‘{’ token
 #define swap(a, b) { uint8_t t = a; a = b; b = t; }
                    ^
In file included from /usr/include/c++/6/bits/stl_pair.h:59:0,
                 from /usr/include/c++/6/utility:70,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/bits/move.h:203:5: error: expected unqualified-id before ‘noexcept’
     noexcept(__is_nothrow_swappable<_Tp>::value)
     ^~~~~~~~
In file included from /usr/include/c++/6/utility:76:0,
                 from /home/pi/.node-gyp/6.13.0/include/node/v8.h:21,
                 from /home/pi/.node-gyp/6.13.0/include/node/node.h:42,
                 from ../src/PCD8544.cc:846:
/usr/include/c++/6/initializer_list:39:37: error: expected ‘}’ before end of line
 #pragma GCC visibility push(default)
                                     ^
/usr/include/c++/6/initializer_list:39:37: error: expected declaration before end of line
pcd8544_rpi.target.mk:92: die Regel für Ziel „Release/obj.target/pcd8544_rpi/src/PCD8544.o“ scheiterte
make: *** [Release/obj.target/pcd8544_rpi/src/PCD8544.o] Fehler 1
make: Verzeichnis „/home/pi/node_modules/pcd8544_rpi/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/pcd8544_rpi
gyp ERR! node -v v6.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-pcd8544-rpi"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pcd8544_rpi@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcd8544_rpi@0.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcd8544_rpi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcd8544_rpi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcd8544_rpi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
pi@raspberrypi:~ $
